---
title: "Summary tables and plots"
author: "Matthew Hamilton & Caroline Gao"
date: "03/08/2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r warning=FALSE, message=FALSE}
library(youthvars)
```

```{r}
data("replication_popl_tb")
data_tb <- replication_popl_tb 
```
```{r}
data("repln_ds_dict_r3", package = "youthvars")
data("aqol_scrg_dict_r3", package = "youthvars")
dictionary_tb <- ready4use::bind_lups(repln_ds_dict_r3,
                                      new_ready4_dict_r3 = aqol_scrg_dict_r3)
```

```{r echo = F}
print_cohort_tbl <- function (df, 
                              bl_fup_vals_chr = c("Baseline","Follow-up"),
                              caption_1L_chr = NULL, 
                              mkdn_tbl_ref_1L_chr = NULL, 
                              output_type_1L_chr,
                              round_var_nm_1L_chr,
                              test_1L_lgl = F,
                              variable_nms_chr) 
{
  df <- df %>%
    dplyr::filter(!label %in% variable_nms_chr)
  valid_var_nms_chr <- df$label %>% unique() %>%
    stringi::stri_replace_all_fixed("_","")
  rename_lup <- tibble::tibble(old_nms_chr = df$label %>% unique(),
                               new_nms_chr = make.unique(valid_var_nms_chr, sep="V")) 
  df$label <- df$label %>% purrr::map_chr(~ifelse(.x %in% rename_lup$old_nms_chr,
                                                  ready4fun::get_from_lup_obj(rename_lup,
                                                                              match_value_xx = .x,
                                                                              match_var_nm_1L_chr = "old_nms_chr",
                                                                              target_var_nm_1L_chr = "new_nms_chr",
                                                                              evaluate_lgl = F),
                                                  .x))
  
    #df$variable <- gsub("\\s*\\([^\\)]+\\)", "",df$variable)
    n_inc_1L_dbl <- data_tb %>% 
      dplyr::filter(!!rlang::sym(round_var_nm_1L_chr) == bl_fup_vals_chr[1]) %>%
      nrow()
    n_fup_1L_dbl <- data_tb %>% 
      dplyr::filter(!!rlang::sym(round_var_nm_1L_chr) == bl_fup_vals_chr[2]) %>%
      nrow()
    if(is.null(caption_1L_chr))
      caption_1L_chr <- knitr::opts_current$get("tab.cap")
    if(is.null(mkdn_tbl_ref_1L_chr))
      mkdn_tbl_ref_1L_chr <- paste0("tab:", 
                                    knitr::opts_current$get("tab.id"))
    if(output_type_1L_chr %in% c("HTML",
                                 "Word"))
      df <- df %>% transform_tb_for_merged_col_1(output_type_1L_chr = output_type_1L_chr)
    if (output_type_1L_chr %in% c("PDF","HTML")) {
        df <- df %>% dplyr::mutate_all(~stringr::str_replace(.x, 
            "%", "\\\\%") %>% stringr::str_replace(",", 
            "\\\\,"))
    }
    if (output_type_1L_chr %in% c("PDF","HTML")) {
        names_chr <- c("", 
                       "", 
                       "(N =", 
                       paste0(n_inc_1L_dbl,
                              ifelse(output_type_1L_chr == "HTML","\\)",")")), 
                       "(N =", 
                       paste0(n_fup_1L_dbl, 
                              ifelse(output_type_1L_chr == "HTML","\\)",")")))
        header_chr <- c(" ", 
                        " ", 
                        Baseline = 2, # Baseline only
                        `Follow-Up` = 2) # Baseline and follow-up
        if(test_1L_lgl){
         names_chr <- c(names_chr,
                         ifelse(output_type_1L_chr == "HTML","*p*","\\textit{p}"))
         header_chr <- c(header_chr, " ")
        }
          
        names(df) <- names_chr
        df %>% kableExtra::kbl(booktabs = T, 
                               caption = caption_1L_chr, 
                               escape = F) %>% 
          kableExtra::kable_styling() %>% 
          kableExtra::column_spec(3:6, 
                                  width = "3em") %>% 
          kableExtra::column_spec(1, bold = T, width = "14em") %>% 
          kableExtra::add_header_above(header_chr) %>% 
          kableExtra::collapse_rows(columns = 1)
    }
    else {
        # df <- df %>% transform_tb_for_merged_col_1(output_type_1L_chr = output_type_1L_chr)
        add_to_row_ls <- NULL 
        df %>% ready4show::print_table(output_type_1L_chr = output_type_1L_chr, 
                                       caption_1L_chr = caption_1L_chr, 
                                       mkdn_tbl_ref_1L_chr = mkdn_tbl_ref_1L_chr, 
                                       use_rdocx_1L_lgl = ifelse(output_type_1L_chr == 
                "Word", 
                T, 
                F), 
                add_to_row_ls = add_to_row_ls, 
                sanitize_fn = force)
    }
}
transform_tb_for_merged_col_1 <- function(df,
                                          output_type_1L_chr = "PDF"){
  df[[1]] <- as.character(df[[1]])
  rle.lengths <- rle(df[[1]])$lengths
  first <- !duplicated(df[[1]])
  df[[1]][!first] <- ""
  if(output_type_1L_chr == "PDF")
    df[[1]][first] <- paste0("\\midrule\\multirow{", rle.lengths, "}{*}{\\textbf{", df[[1]][first], "}}")
  return(df)
}
```

## Cohort description table
```{r participantstb, tab.cap='Participant characteristics', tab.id = 'participantstb', results="asis"}
variable_nms_chr <- c("d_age","d_sexual_ori_s",
                      "d_ATSI","d_studying_working","d_relation_s")
df <- make_descv_stats_tbl(data_tb = data_tb, 
                           key_var_nm_1L_chr = "round",
                           key_var_vals_chr = data_tb %>% dplyr::pull(round) %>% unique() %>% as.character(),
                           dictionary_tb = dictionary_tb,
                           variable_nms_chr = variable_nms_chr,
                           nbr_of_digits_1L_int = 2)
df %>%
  print_cohort_tbl(#caption_1L_chr = "Cohort descriptives table",
                   #mkdn_tbl_ref_1L_chr = "", 
    bl_fup_vals_chr = c("Baseline","Follow-up"),
    output_type_1L_chr = ifelse(knitr::is_html_output(),"HTML","PDF"),
    round_var_nm_1L_chr = "round",
    variable_nms_chr = variable_nms_chr)
```
## Outcome summary table
```{r outcomestb, tab.cap='Outcomes table', tab.id = 'outcomestb', results="asis"}
variable_nms_chr <- c("k6_total", "phq9_total", "bads_total", "gad7_total")
df <- make_descv_stats_tbl(data_tb = data_tb, 
                          key_var_nm_1L_chr = "round",
                          key_var_vals_chr = data_tb %>% dplyr::pull(round) %>% unique() %>% as.character(),
                          dictionary_tb = dictionary_tb,
                          variable_nms_chr = variable_nms_chr,
                          test_1L_lgl = T,
                          nbr_of_digits_1L_int = 2)
df %>%
  print_cohort_tbl(bl_fup_vals_chr = c("Baseline","Follow-up"),
                   output_type_1L_chr = ifelse(knitr::is_html_output(),"HTML","PDF"),
                   round_var_nm_1L_chr = "round",
                   test_1L_lgl = T,
                   variable_nms_chr = variable_nms_chr)
```

```{r}
data_tb <- data_tb %>%
  add_participation_var() 
df <- make_descv_stats_tbl(data_tb = data_tb  %>%
                             dplyr::filter(round == "Baseline"), #
                           key_var_nm_1L_chr = "participation",
                           key_var_vals_chr = data_tb$participation %>% unique(),
                           dictionary_tb = dictionary_tb,
                           variable_nms_chr = variable_nms_chr,
                           test_1L_lgl = T,
                           nbr_of_digits_1L_int = 2)
# df %>%
#   print_cohort_tbl(bl_fup_vals_chr = c("Baseline","Follow-up"),
#                    output_type_1L_chr = ifelse(knitr::is_html_output(),"HTML","PDF"),
#                    round_var_nm_1L_chr = "round",
#                    test_1L_lgl = T,
#                    variable_nms_chr = variable_nms_chr)
```


```{r}
  # descv_tbl_ls <- list(
  #                      ,
  #                      bl_cors_tb = transform_ds_for_tstng(data_tb,
  #                                                          depnt_var_nm_1L_chr = ds_descvs_ls$utl_wtd_var_nm_1L_chr,
  #                                                          dep_var_max_val_1L_dbl = Inf,
  #                                                          candidate_predrs_chr = ds_descvs_ls$candidate_predrs_chr,
  #                                                          round_var_nm_1L_chr = ds_descvs_ls$round_var_nm_1L_chr,
  #                                                          round_val_1L_chr = ds_descvs_ls$round_vals_chr[1]) %>%
  #                        make_corstars_tbl_xx(result_chr = "none"),##
  #                      fup_cors_tb = transform_ds_for_tstng(data_tb,
  #                                                           depnt_var_nm_1L_chr = ds_descvs_ls$utl_wtd_var_nm_1L_chr,
  #                                                           dep_var_max_val_1L_dbl = Inf,
  #                                                           candidate_predrs_chr = ds_descvs_ls$candidate_predrs_chr,
  #                                                           round_var_nm_1L_chr = ds_descvs_ls$round_var_nm_1L_chr,
  #                                                           round_val_1L_chr = ds_descvs_ls$round_vals_chr[2]) %>%
  #                        make_corstars_tbl_xx(result_chr = "none"),
  #                      cors_with_utl_tb = make_cors_with_utl_tbl(data_tb,
  #                                                                ds_descvs_ls = ds_descvs_ls),
  #                      ds_descvs_ls = ds_descvs_ls)
  # descv_tbl_ls$predr_pars_and_cors_tb <- make_predr_pars_and_cors_tbl(data_tb,
  #                                                                     ds_descvs_ls = ds_descvs_ls,
  #                                                                     descv_tbl_ls = descv_tbl_ls,
  #                                                                     dictionary_tb = ds_descvs_ls$dictionary_tb,
  #                                                                     nbr_of_digits_1L_int = nbr_of_digits_1L_int,
  #                                                                     predictors_lup = predictors_lup)
```

