#' youthvars: Youth Mental Health Variables Modelling Toolkit
#'
#' Classes that describe the structural properties of variables
#' commonly present in youth mental health datasets and some (where
#' freely available) related scoring algorithms.  The main motivation for
#' this package is to enable data integrity tools that ensure that
#' methods are applied to the appropriate data structures.  This
#' development version of the youthvars package has been made available
#' as part of the process of testing and documenting the package. The
#' documentation for this package has been automatically generated by the
#' ready4fun package and is therefore quite rudimentary. Human authored
#' documentation will follow in 2021.  If you have any questions, please
#' contact the authors (matthew.hamilton@orygen.org.au).
#'
#' To learn more about youthvars, start with the vignettes:
#' `browseVignettes(package = "youthvars")`
#'
"_PACKAGE"
