#' youthvars: Youth Mental Health Variables Description Toolkit
#'
#' Tools to describe, summarise and score types of data commonly
#' present in youth mental health collections.  The main motivation for
#' this package is to facilitate automated data integrity checks, ensure
#' that methods are applied to the appropriate data structures and
#' streamline reporting of descriptive statistics.  This development
#' version of the youthvars package has been made available as part of
#' the process of testing and documenting the package. The documentation
#' for this package has been automatically generated by the ready4fun
#' package and is therefore quite rudimentary. Human authored
#' documentation will follow in 2021.  If you have any questions, please
#' contact the authors (matthew.hamilton@orygen.org.au).
#'
#' To learn more about youthvars, start with the vignettes:
#' `browseVignettes(package = "youthvars")`
#'
"_PACKAGE"
